[general]
import = ["~/.config/alacritty/themes/solarized_dark.toml"]

[window]
opacity = 1.00

[font]
size = 14
normal      =  { family = "Liberation Mono" }
bold        =  { family = "Liberation Mono" }
italic      =  { family = "Liberation Mono" }
bold_italic =  { family = "Liberation Mono" }

[cursor]
style = {shape = "Block"}

[mouse]
hide_when_typing = true
