[general]
import = ["~/.config/alacritty/themes/catpuccin-mocha.toml"]

[window]
opacity = 1.00
decorations="none"

[font]
size = 14
normal      =  { family = "DepartureMono Nerd Font Mono" }
bold        =  { family = "DepartureMono Nerd Font Mono" }
italic      =  { family = "DepartureMono Nerd Font Mono" }
bold_italic =  { family = "DepartureMono Nerd Font Mono" }

[cursor]
style = {shape = "Block"}

[mouse]
hide_when_typing = true
